# Generated by Django 4.1.7 on 2024-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='')),
            ],
            options={
                'db_table': 'custom_table_name',
            },
        ),
    ]
