# Generated by Django 4.1.7 on 2024-04-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Phone', models.IntegerField(default='', max_length=20)),
            ],
        ),
    ]
