# Generated by Django 4.1.7 on 2024-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlite_proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='Phone',
            field=models.IntegerField(default=''),
        ),
    ]
