# Generated by Django 4.1.7 on 2024-04-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlite_proj', '0002_alter_info_age_alter_info_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='info',
            table='custom_table_name',
        ),
    ]
