# Generated by Django 4.1.7 on 2024-04-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlite_proj', '0003_alter_info_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='MyInfo',
        ),
    ]
